%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/chinook/multisense/imu/imu_data"
image0_topic: "/chinook/multisense/left/image_rect_mono"
image1_topic: "/chinook/multisense/right/image_rect_mono"
output_path: "/tmp/"

cam0_calib: "multisense-camera-left.yaml"
cam1_calib: "multisense-camera-right.yaml"
image_width: 1024
image_height: 544
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.000,  0.000, 0.000, 0.215,
           0.000, 1.000, 0.000, 0.035,
           0.000, 0.000, 1.000, 0.548,
           0.000, 0.000, 0.000, 1.000]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.000,  0.000, 0.000, 0.215,
           0.000, 1.000, 0.000, -0.035,
           0.000, 0.000, 1.000, 0.548,
           0.000, 0.000, 0.000, 1.000]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
